apiVersion: batch/v1
kind: Job
metadata:
  generateName: app-slack-notification-
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
      - name: post-install-job
        image: "alpine:3.3"
        command: ["/bin/sleep", "10"]
      restartPolicy: Never
  backoffLimit: 2
