{{- if .Values.hook.test_pulsar_producer }}
apiVersion: batch/v1
kind: Job
metadata:
  generateName: test-pulsar-producer-
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      serviceAccountName: {{ template "pulsar.fullname" . }}-hook-serviceaccount
      containers:
        - name: pulsar-producer
          image: "bitnami/kubectl"
          args:
            - "kubectl exec -n sn-platform-test sn-platform-slim-toolset-0 -- bin/pulsar-admin clusters list"
      restartPolicy: Never
  backoffLimit: 2
{{- end }}
